import axios from "axios";
import { GetStaticProps } from "next";
import Head from "next/head";
import { Movie } from "../types";
import Pagination from "../components/shared/Pagination";
import MovieList from "../components/Movie/MovieList";

interface Home {
  movies: Movie[];
  moviesCount: number;
}

export default function Home({ movies, moviesCount }: Home) {
  return (
    <>
      <Head>
        <title>Movie House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="xs-12 col-sm-7 col-md-9 col-xl-10">
        <div className="row mt-4">
          <MovieList movies={movies} />
        </div>

        <div className="row mt-5">
          <Pagination itemsCount={moviesCount} currentPage={1} />
        </div>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const fetch1 = axios.get(`${process.env.API_BASE_URL}/api/v1/movies?page=1`);
  const fetch2 = axios.get(`${process.env.API_BASE_URL}/api/v1/movies?page=2`);
  const fetch3 = axios.get(`${process.env.API_BASE_URL}/api/v1/movies?page=3`);

  const res = await Promise.all([fetch1, fetch2, fetch3]);
  const data = res.map((fetchItem) => fetchItem.data.data);

  return {
    props: {
      movies: [...data[0], ...data[1], ...data[2]],
      moviesCount: res[0].data.metadata.total_count
    },
  };
};
