import axios from 'axios';
import { GetStaticProps } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

interface Home {
  movies: [{
    id: number;
    title: string;
    poster: string;
    year: string;
    released: string;
    plot: string;
    genres: string[];
  }]
}

export default function Home({ movies }: Home) {
  return (
    <>
      <Head>
        <title>Movie House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="xs-12 col-sm-7 col-md-9 col-xl-10">

          <div className="row mt-4">
            {movies.length ? movies.map(movie => (
              <div key={movie.id} className="col-12 col-sm-6 col-md-4 col-xl-3 col-xxl-2 mt-3">
                <article className="card movie-card">
                  <Image src={movie.poster} width={290} height={190} className="card-Image-top" alt="..." />
                  <div className="card-body">
                    <h2 className="h5" title={movie.title}>{movie.title}</h2>
                    <p className="card-text">{movie.plot}</p>
                    <Link href={`/movie/${movie.id}`} className="btn btn-primary btn-sm button-62">
                      Check out
                    </Link>
                  </div>
                </article>
              </div>
            )) : null}

          </div>
        </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
    const fetch1 = axios.get('https://moviesapi.ir/api/v1/movies?page=1');
    const fetch2 = axios.get('https://moviesapi.ir/api/v1/movies?page=2');
    const fetch3 = axios.get('https://moviesapi.ir/api/v1/movies?page=3');

    const res = await Promise.all([fetch1, fetch2, fetch3])
    const data = res.map(fetchItem => fetchItem.data.data);

    return {
      props: {
        movies: [...data[0], ...data[1], ...data[2]]
      }
    }
}
