import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="xs-12 col-sm-7 col-md-9 col-xl-10">

          <div className="row mt-4">

            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..." />
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>

          </div>
          <div className="row mt-4">

            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..." />
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>

          </div>
          <div className="row mt-4">

            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..." />
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cardes content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card movie-card">
                <Image src={'/movie-1.jpg'} width={290} height={190} className="card-Image-top" alt="..."/>
                <div className="card-body">
                  <p className="card-text">Some quick example text to build on the card title and make up the bulk of the cards content.</p>
                  <button type="button" className="btn btn-primary btn-sm button-62">
                    Check out
                  </button>
                </div>
              </div>
            </div>

          </div>
          
        </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}
